### PR TITLE
Fix download file issue

### PR DESCRIPTION
**Pull request by KonradIT**
fixes downloading file issue, now can detect last folder and last file taken.

### CODE REVIEW

**Comment by Splinter0** [comment]
Thanks man, i fixed the connection crash issue, and also i automated the password ( doesn't ask for it ) using one of your link. I added your changes you did and soon a will pull everything 
Thanks a lot again man, i hope you'll continue collaborate with me

Uh and also, it's ok if i use the email to ask you some stuff?

**Comment by KonradIT** [comment]
@Splinter0 cool, how did you get the password for the camera? /camera/sd and /bacpac/sd don't work on HERO4 Black. I'd suggest recognising the camera and then adapting the urls and methods. [I used thus in Python to detect which camera is connected](https://github.com/KonradIT/GoProStream/blob/master/GoProStream.py#L47). Works with HERO3, HERO4, HERO5.

My mail is: mail at chernowii dot com

**Comment by Splinter0** [comment]
Yeah, now i'm having dinner XD i was doing a function to detect the camera.
by the way , is there a way we can edit the same repo ( but not the official one? the one master in my profile )

**Comment by Splinter0** [comment]
i'm using a dictionary also to detect the camera... with your FW ID : you putted on goprowifihack

**Comment by Splinter0** [comment]
i'm gonna finish that function and then pull everything on the main repo so you can fork it in this one and we can you it ad a shared one if you want

**Comment by KonradIT** [comment]
I'd say I regularly pull updates from your repo and then I PR and you merge. What camera do you have?

**Comment by Splinter0** [comment]
I don't know what PR and merge ( merge a bit ) mean XD, but i have a hero3+ ( yeah i know not the best one ), but i have a friend that has a 4 and a 5 and i can ask him for help maybe XD

**Comment by KonradIT** [comment]
@Splinter0 https://help.github.com/articles/merging-a-pull-request/

I have a HERO4 Black, Session and HERO3 Black. Soon a HERO5 I guess. Also, will you get a Karma drone?

**Comment by Splinter0** [comment]
If i have to say it, i don't really like the Karma drone. I love drones and especially i love build them ( i'm building a custom drone now ) and looking at the Karma doesn't attract me a lot XD.
But who knows. Instead i'm probably gonna buy an hero5 session, i know it isn't the best one but it's really good and not that expansive

**Comment by KonradIT** [comment]
My HERO4 Black is still the best camera I have. I'll probably buy 2x Xiaomi Yi 4K (you heard it here first) and a HERO5 Session.

As per the Karma, I'll wait for Karma 2.

**Comment by Splinter0** [comment]
uh and also... wait to see the updates i'm making before your pull with your new stuff. so you have the updated version of my repo e when you have updates i can merge

**Comment by Splinter0** [comment]
by the way i included your updates manually ( cause i'm a noob ) and after a finish the detect function you'll see them in the next pull i do into my repo

**Comment by KonradIT** [comment]
Cool, you could also add me to the project's maintainers so I can add code too.

**Comment by Splinter0** [comment]
sure i'll do it now

**Comment by Splinter0** [comment]
But don't pull anything without consulting each others ( same for me )

**Comment by Splinter0** [comment]
i mean push

**Pull request closed without merging**
